config/routes.rb
Onemdl::Application.routes.draw do
  
  #put our concerns first
  concern :systemable do
    resources :systems, concerns: :pageable
  end
  
  concern :pageable do
    get 'page/:page', action: :index, on: :collection
  end
  
  # don't forget pagination MUST be above nested resources or URLs will break
  
  # routes home to root
  root 'staticpages#home'
  
  # static pages routing
  match '/help',    to: 'staticpages#help',     via: 'get'
  match '/about',   to: 'staticpages#about',    via: 'get'
  match '/contact', to: 'staticpages#contact',  via: 'get'
  match '/faq',     to: 'staticpages#faq',      via: 'get'
  match '/support', to: 'staticpages#support',  via: 'get'
  match '/tos',     to: 'staticpages#tos',      via: 'get'
  
  # routes for signup, login and logout pages
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  # storing user sessions
  resources :sessions
  
  # site wide announcements
  resources :announcements
  match 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement', via: :get
  
  # statistics
  resources :statistics
  
  ##############################################################################
  # :addresses  
  resources :addresses, concerns: :pageable
    
  ##############################################################################
  # :activities
  resources :activities, concerns: :pageable
  
  ##############################################################################
  # :users and nested resources
  resources :users, concerns: :pageable
  
  ##############################################################################
  # :manufacturers and nested resources
  resources :manufacturers, concerns: :pageable do
    resources :device_models, concerns: :pageable
  end
  
  ##############################################################################
  # :device_types and nested resources
  resources :device_types, concerns: :pageable do
    resources :device_models, concerns: :pageable
  end
  
  ##############################################################################
  # :device_models and nested resources
  resources :device_models, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # :environments and nested resources
  resources :environments, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # :service_levels and nested resources
  resources :service_levels, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # :support_levels and nested resources
  resources :support_levels, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # :relationships and nested resources
  resources :relationships, concerns: :pageable do
    resources :organisations, concerns: :pageable
  end
  
  ##############################################################################
  # :organisations and nested resources
  resources :organisations, shallow: true, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
    
    resources :license_types,     concerns: :pageable
    resources :licenses,          concerns: :pageable
    resources :operating_systems, concerns: :pageable
    resources :addresses,         concerns: :pageable
    resources :people,            concerns: :pageable
    
    # resources :note do
  #     get 'page/:page', :action => :index, :on => :collection
  #   end
  end
  
  ##############################################################################
  # :license_types and nested resources
  resources :license_types, shallow: true, concerns: :pageable do
    resources :licenses, concerns: :pageable
  end
  
  ##############################################################################
  # :licenses and nested resources
  resources :licenses, shallow: true, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # operating_system_families and nested resources
  resources :operating_system_families, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
    
    resources :operating_systems, concerns: :pageable
  end
  
  resources :operating_systems, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # :systems and nested resources
  resources :systems, concerns: :pageable do
    resources :network_interfaces, concerns: :pageable
    resources :consoles, concerns: :pageable
  end
  
  ##############################################################################
  # :persons and nested resources
  resources :people, concerns: :pageable
  
  ##############################################################################
  # :addresses and nested resources
  resources :addresses, concerns: :pageable
  
  ##############################################################################
  # :network_uses and nested resources
  resources :network_uses, concerns: :pageable do
    resources :network_interfaces, concerns: :pageable
  end
  
  ##############################################################################
  # :network_interfaces
  resources :network_interfaces, concerns: :pageable

  ##############################################################################
  # :consoles
  resources :consoles, concerns: :pageable
  
  resources :onemdl_settings, :only => [:index, :edit]
  
  match '/onemdl_settings',      to: 'onemdl_settings#index',    via: 'get'
  match '/onemdl_settings/edit', to: 'onemdl_settings#edit',     via: 'get'
end

app/models/operating_system.rb
# OneMDL is a ruby on rails based application designed to collate information
# about IT assets. It is designed to be most useful to System Administrators
# and Service Desk personal.
# 
# Copyright (C) 2013-2015 David Marsh
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class OperatingSystem < ActiveRecord::Base
  has_paper_trail
  include PublicActivity::Common
  
  # friendly IDs, better URLs
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  
  # regenerate new slugs?
  def should_generate_new_friendly_id?
    name_changed?
  end
  
  # Try building a slug based on the following fields in
  # increasing order of specificity.
  def slug_candidates
    [
      :name,
      # [:name, :organisation_id]
    ]
  end
  
  before_validation :strip_blanks
  
  # belongs to
  belongs_to :organisation
  belongs_to :operating_system_family
  
  
  
  
  # has many
  has_many :systems, dependent: :restrict_with_error
  
  # validations
  validates :name, presence: true, uniqueness: { case_sensitive: false, :scope => :release,
     message: "Name and Release combination already present" }
  validates :release, presence: true
  validates :operating_system_family_id, presence: true
  
  
  
  
  before_destroy :protect_unknown_none
  
  
  
  private
  
  def os_and_release
    "#{name} (#{release})"
  end
  
  def protect_unknown_none
    !name.downcase.eql?("unknown") and !name.downcase.eql?("none")
  end
  
  protected
  
  def strip_blanks
    self.name = self.name.strip
  end
  
end

app/controllers/operating_systems_controller.rb
# OneMDL is a ruby on rails based application designed to collate information
# about IT assets. It is designed to be most useful to System Administrators
# and Service Desk personal.
# 
# Copyright (C) 2013-2015 David Marsh
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class OperatingSystemsController < ApplicationController
  respond_to :html, :xml, :json
  helper_method :sort_column, :sort_direction

  def index
    @operating_systems = OperatingSystem.order(sort_column + " " + sort_direction).page(params[:page])
    respond_with(@operating_systems)
  end

  def show
    @operating_system = OperatingSystem.friendly.find(params[:id])
    respond_with(@operating_system)
  end

  def new
    @operating_system = OperatingSystem.new
    respond_with(@operating_system)
  end

  def create
    @operating_system = OperatingSystem.new(operating_system_params)
  
    if @operating_system.save
      # write a create message to the activity log
      @operating_system.create_activity :create, owner: current_user
      flash[:info] = "Successfully created OperatingSystem '" + @operating_system.name + "'"
    else
      flash[:error] = "Could not create OperatingSystem '" + @operating_system.name + "'"
    end
  
    respond_with(@operating_system)
  end

  def edit
    @operating_system = OperatingSystem.friendly.find(params[:id])
    respond_with(@operating_system)
  end

  def update
    @operating_system = OperatingSystem.friendly.find(params[:id])
  
    if @operating_system.update_attributes(operating_system_params)
      # write an update message to the activity log
      @operating_system.create_activity :update, owner: current_user
      flash[:info] = "Successfully updated OperatingSystem '" + @operating_system.name + "'"
    else
      flash[:error] = "Could not update OperatingSystem '" + @operating_system.name + "'"
    end
  
    respond_with(@operating_system)
  end

  def destroy
    @operating_system = OperatingSystem.friendly.find(params[:id])
  
    # write an update message to the activity log, it fails with a "cannot call create unless the parent is saved" inside the if statement, so I've put it here. It works out anyway, as we can show both successes and failures
    @operating_system.create_activity :destroy, owner: current_user
    if @operating_system.destroy
      flash[:info] = "Successfully deleted OperatingSystem '" + @operating_system.name + "'"
    else
      flash[:error] = "Could not delete OperatingSystem '" + @operating_system.name + "'"
    end
  
    respond_with(@operating_system)
  end

  private

  # for sorting columns
  def sort_column
    OperatingSystem.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  # for allowing editing on fields
  def operating_system_params
    params.require(:operating_system).permit!
  end
  end

app/views/operating_systems/_form.html.haml
= simple_form_for @operating_system do |f|
  = f.error_notification
  
  = f.input       :name, hint: "Operating system name"
  = f.input       :release
  = f.association :operating_system_family, include_blank: false, prompt: "Choose an OS family", collection: OperatingSystemFamily.order('name ASC')
  = f.association :organisation,    include_blank: false, prompt: "Choose an organisation",  collection: Organisation.order('name ASC')
  = f.input       :release_date,    include_blank: true
  = f.input       :end_of_support,  include_blank: true
  = f.input       :description,     hint: "#{t('hint_description')} operating system"
  
  = f.error :base
  = f.button :submit, :class => 'btn btn-primary'
  .btn-group.task_controller
    %a{:class => 'btn btn-danger dropdown-toggle', 'data-toggle' => 'dropdown', :href => '#'}
      #{t('delete')}.humanize
      %span{:class => 'caret'}
    %ul.dropdown-menu
      %li= link_to "Delete '#{f.object.name}'?", @operating_system, data: { confirm: 'Are you sure?' }, :method => :delete
  or
  = link_to "#{t('cancel')}".humanize, :back

app/views/operating_systems/_head.html.haml
- content_for(:title, t('operating_system').pluralize.humanize)

- content_for(:index_tab, operating_systems_path)
- content_for(:new_tab, new_operating_system_path)

= render 'layouts/heading'
= render 'layouts/tabs'

app/views/operating_systems/edit.html.haml
- content_for(:show_button_path, operating_system_path(@operating_system))

= render 'head'

= render 'form'

app/views/operating_systems/index.html.haml
/ OperatingSystems

=render 'head'

- if @operating_systems.empty?
  %p= empty_msg('operating_system', '')
- else
  %table.table.table-hover.table-condensed
    %tbody
      %thead
        %th
          = sortable "slug"
          %span{:class => 'caret'}
        %th
          = sortable "name"
          %span{:class => 'caret'}
        %th
          = sortable "release"
          %span{:class => 'caret'}
        %th= link_to t('operating_system_family').singularize.humanize, operating_system_families_path
        %th= link_to t('organisation').singularize.humanize, organisations_path
        %th
          = sortable "release_date"
          %span{:class => 'caret'}
        %th
          = sortable "end_of_support"
          %span{:class => 'caret'}        
        %th= link_to t('system').pluralize.humanize, systems_path
      - @operating_systems.each do |r|
        %tr
          %td= link_to r.slug, r
          %td= link_to r.name, r
          %td= r.release
          %td= link_to r.operating_system_family.name, operating_system_family_path(r.operating_system_family.slug)
          %td= link_to r.organisation.name, organisation_path(r.organisation.slug)
          %td= r.release_date
          %td= r.end_of_support
          %td= link_to r.systems.count, operating_system_systems_path(r.slug)
  = paginate @operating_systems

app/views/operating_systems/show.html.haml
/ OperatingSystem
- content_for(:edit_button_path, edit_operating_system_path)

= render 'head'

= show_for @operating_system do |f|
  .well
    %b= f.attribute :name
    = f.attribute :release
    = f.association :operating_system_family
    = f.association :organisation
    = f.attribute :release_date
    = f.attribute :end_of_support
    = simple_format f.attribute :description
  .well
    = f.association :systems do
      %ul
        - @operating_system.systems.each do |system|
          %li= link_to system.name, system_path(system.slug)
    - if @operating_system.systems.empty?
      %p= empty_msg('system', 'operating_system')
  .well.muted
    = f.attribute :created_at, :format => :iso8601
    = f.attribute :updated_at, :format => :iso8601