config/routes.rb
Onemdl::Application.routes.draw do
  
  #put our concerns first
  concern :systemable do
    resources :systems, concerns: :pageable
  end
  
  concern :pageable do
    get 'page/:page', action: :index, on: :collection
  end
  
  # don't forget pagination MUST be above nested resources or URLs will break
  
  # routes home to root
  root 'staticpages#home'
  
  # static pages routing
  match '/help',    to: 'staticpages#help',     via: 'get'
  match '/about',   to: 'staticpages#about',    via: 'get'
  match '/contact', to: 'staticpages#contact',  via: 'get'
  match '/faq',     to: 'staticpages#faq',      via: 'get'
  match '/support', to: 'staticpages#support',  via: 'get'
  match '/tos',     to: 'staticpages#tos',      via: 'get'
  
  # routes for signup, login and logout pages
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  # storing user sessions
  resources :sessions
  
  # site wide announcements
  resources :announcements
  match 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement', via: :get
  
  # statistics
  resources :statistics
  
  ##############################################################################
  # :addresses  
  resources :addresses, concerns: :pageable
    
  ##############################################################################
  # :activities
  resources :activities, concerns: :pageable
  
  ##############################################################################
  # :users and nested resources
  resources :users, concerns: :pageable
  
  ##############################################################################
  # :manufacturers and nested resources
  resources :manufacturers, concerns: :pageable do
    resources :device_models, concerns: :pageable
  end
  
  ##############################################################################
  # :device_types and nested resources
  resources :device_types, concerns: :pageable do
    resources :device_models, concerns: :pageable
  end
  
  ##############################################################################
  # :device_models and nested resources
  resources :device_models, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # :environments and nested resources
  resources :environments, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # :service_levels and nested resources
  resources :service_levels, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # :support_levels and nested resources
  resources :support_levels, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # :relationships and nested resources
  resources :relationships, concerns: :pageable do
    resources :organisations, concerns: :pageable
  end
  
  ##############################################################################
  # :organisations and nested resources
  resources :organisations, shallow: true, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
    
    resources :license_types,     concerns: :pageable
    resources :licenses,          concerns: :pageable
    resources :operating_systems, concerns: :pageable
    resources :addresses,         concerns: :pageable
    resources :people,            concerns: :pageable
    
    # resources :note do
  #     get 'page/:page', :action => :index, :on => :collection
  #   end
  end
  
  ##############################################################################
  # :license_types and nested resources
  resources :license_types, shallow: true, concerns: :pageable do
    resources :licenses, concerns: :pageable
  end
  
  ##############################################################################
  # :licenses and nested resources
  resources :licenses, shallow: true, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # operating_system_families and nested resources
  resources :operating_system_families, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
    
    resources :operating_systems, concerns: :pageable
  end
  
  resources :operating_systems, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # :systems and nested resources
  resources :systems, concerns: :pageable do
    resources :network_interfaces, concerns: :pageable
    resources :consoles, concerns: :pageable
  end
  
  ##############################################################################
  # :persons and nested resources
  resources :people, concerns: :pageable
  
  ##############################################################################
  # :addresses and nested resources
  resources :addresses, concerns: :pageable
  
  ##############################################################################
  # :network_uses and nested resources
  resources :network_uses, concerns: :pageable do
    resources :network_interfaces, concerns: :pageable
  end
  
  ##############################################################################
  # :network_interfaces
  resources :network_interfaces, concerns: :pageable

  ##############################################################################
  # :consoles
  resources :consoles, concerns: :pageable
  
  resources :onemdl_settings, :only => [:index, :edit]
  
  match '/onemdl_settings',      to: 'onemdl_settings#index',    via: 'get'
  match '/onemdl_settings/edit', to: 'onemdl_settings#edit',     via: 'get'
end

app/controllers/device_types_controller.rb
# OneMDL is a ruby on rails based application designed to collate information
# about IT assets. It is designed to be most useful to System Administrators
# and Service Desk personal.
# 
# Copyright (C) 2013-2015 David Marsh
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class DeviceTypesController < ApplicationController
  respond_to :html, :xml, :json
  helper_method :sort_column, :sort_direction
  
  def index
    @device_types = DeviceType.order(sort_column + " " + sort_direction).page(params[:page])
    respond_with(@device_types)
  end
  
  def show
    @device_type = DeviceType.friendly.find(params[:id])
    respond_with(@device_type)
  end
  
  def new
    @device_type = DeviceType.new
    respond_with(@device_type)
  end
  
  def create
    @device_type = DeviceType.new(device_type_params)
    
    if @device_type.save
      # write a create message to the activity log
      @device_type.create_activity :create, owner: current_user
      flash[:info] = "Successfully created device type '" + @device_type.name + "'"
    else
      flash[:error] = "Could not create device type '" + @device_type.name + "'"
    end
    
    respond_with(@device_type)
  end
  
  def edit
    @device_type = DeviceType.friendly.find(params[:id])
    respond_with(@device_type)
  end
  
  def update
    @device_type = DeviceType.friendly.find(params[:id])
    
    if @device_type.update_attributes(device_type_params)
      # write an update message to the activity log
      @device_type.create_activity :update, owner: current_user
      flash[:info] = "Successfully updated device type '" + @device_type.name + "'"
    else
      flash[:error] = "Could not update device type '" + @device_type.name + "'"
    end
    
    respond_with(@device_type)
  end
  
  def destroy
    @device_type = DeviceType.friendly.find(params[:id])
    
    # write an update message to the activity log, it fails with a "cannot call create unless the parent is saved" inside the if statement, so I've put it here. It works out anyway, as we can show both successes and failures
    @device_type.create_activity :destroy, owner: current_user
    if @device_type.destroy
      flash[:info] = "Successfully deleted device type '" + @device_type.name + "'"
    else
      flash[:error] = "Could not delete device type '" + @device_type.name + "'"
    end
    
    respond_with(@device_type)
  end
  
  private
  
  # for sorting columns
  def sort_column
    DeviceType.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end
  
  # for allowing editing on fields
  def device_type_params
    params.require(:device_type).permit!
  end
end

app/views/device_types/_form.html.haml
= simple_form_for @device_type do |f|
  = f.error_notification
  
  = f.input :name
  = f.input :description
  
  = f.error :base
  = f.button :submit, :class => 'btn btn-primary'
  
  .btn-group.task_controller
    %a{:class => 'btn btn-danger dropdown-toggle', 'data-toggle' => 'dropdown', :href => '#'}
      #{t('delete').humanize}
      %span{:class => 'caret'}
    %ul.dropdown-menu
      %li= link_to "#{t('delete')} '#{f.object.name}'?".humanize, @device_type, data: { confirm: 'Are you sure?' }, :method => :delete
  or
  = link_to "#{t('cancel')}".humanize, :back

app/views/device_types/_head.html.haml
- content_for(:title, t('device_type').pluralize.humanize)

- content_for(:index_tab, device_types_path)
- content_for(:new_tab, new_device_type_path)

= render 'layouts/heading'
= render 'layouts/tabs'

app/views/device_types/edit.html.haml
- content_for(:show_button_path, device_type_path(@device_type))

= render 'head'

= render 'form'

app/views/device_types/index.html.haml
/ DeviceTypes

=render 'head'

- if @device_types.empty?
  %p= empty_msg('device_type', '')
- else
  %table.table.table-hover.table-condensed
    %tbody
      %thead
        %th
          = sortable "slug"
          %span{:class => 'caret'}
        %th
          = sortable "name"
          %span{:class => 'caret'}
        %th
          = sortable "description"
          %span{:class => 'caret'}
        %th= link_to t('device_model').pluralize.humanize, device_models_path
      - @device_types.each do |r|
        %tr
          %td= link_to r.slug, r
          %td= link_to r.name, r
          %td= r.description
          %td= link_to r.device_models.count, device_type_device_models_path(r.slug)
  = paginate @device_types

app/views/device_types/show.html.haml
/ DeviceType
- content_for(:edit_button_path, edit_device_type_path(@device_type))

= render 'head'

= show_for @device_type do |f|
  .well
    %b= f.attribute :name
    = simple_format f.attribute :description
  .well
    = f.association :device_models do
      %ul
        - @device_type.device_models.each do |device_model|
          %li= link_to device_model.name, device_model_path(device_model.slug)
    - if @device_type.device_models.empty?
      %p= empty_msg('device_model', 'device_type')
  .well.muted
    = f.attribute :created_at, :format => :iso8601
    = f.attribute :updated_at, :format => :iso8601