config/routes.rb
Onemdl::Application.routes.draw do
  
  #put our concerns first
  concern :systemable do
    resources :systems, concerns: :pageable
  end
  
  concern :pageable do
    get 'page/:page', action: :index, on: :collection
  end
  
  # don't forget pagination MUST be above nested resources or URLs will break
  
  # routes home to root
  root 'staticpages#home'
  
  # static pages routing
  match '/help',    to: 'staticpages#help',     via: 'get'
  match '/about',   to: 'staticpages#about',    via: 'get'
  match '/contact', to: 'staticpages#contact',  via: 'get'
  match '/faq',     to: 'staticpages#faq',      via: 'get'
  match '/support', to: 'staticpages#support',  via: 'get'
  match '/tos',     to: 'staticpages#tos',      via: 'get'
  
  # routes for signup, login and logout pages
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  # storing user sessions
  resources :sessions
  
  # site wide announcements
  resources :announcements
  match 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement', via: :get
  
  # statistics
  resources :statistics
  
  ##############################################################################
  # :addresses  
  resources :addresses, concerns: :pageable
    
  ##############################################################################
  # :activities
  resources :activities, concerns: :pageable
  
  ##############################################################################
  # :users and nested resources
  resources :users, concerns: :pageable
  
  ##############################################################################
  # :manufacturers and nested resources
  resources :manufacturers, concerns: :pageable do
    resources :device_models, concerns: :pageable
  end
  
  ##############################################################################
  # :device_types and nested resources
  resources :device_types, concerns: :pageable do
    resources :device_models, concerns: :pageable
  end
  
  ##############################################################################
  # :device_models and nested resources
  resources :device_models, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # :environments and nested resources
  resources :environments, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # :service_levels and nested resources
  resources :service_levels, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # :support_levels and nested resources
  resources :support_levels, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # :relationships and nested resources
  resources :relationships, concerns: :pageable do
    resources :organisations, concerns: :pageable
  end
  
  ##############################################################################
  # :organisations and nested resources
  resources :organisations, shallow: true, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
    
    resources :license_types,     concerns: :pageable
    resources :licenses,          concerns: :pageable
    resources :operating_systems, concerns: :pageable
    resources :addresses,         concerns: :pageable
    resources :people,            concerns: :pageable
    
    # resources :note do
  #     get 'page/:page', :action => :index, :on => :collection
  #   end
  end
  
  ##############################################################################
  # :license_types and nested resources
  resources :license_types, shallow: true, concerns: :pageable do
    resources :licenses, concerns: :pageable
  end
  
  ##############################################################################
  # :licenses and nested resources
  resources :licenses, shallow: true, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # operating_system_families and nested resources
  resources :operating_system_families, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
    
    resources :operating_systems, concerns: :pageable
  end
  
  resources :operating_systems, concerns: :systemable do
    get 'page/:page', :action => :index, :on => :collection
  end
  
  ##############################################################################
  # :systems and nested resources
  resources :systems, concerns: :pageable do
    resources :network_interfaces, concerns: :pageable
    resources :consoles, concerns: :pageable
  end
  
  ##############################################################################
  # :persons and nested resources
  resources :people, concerns: :pageable
  
  ##############################################################################
  # :addresses and nested resources
  resources :addresses, concerns: :pageable
  
  ##############################################################################
  # :network_uses and nested resources
  resources :network_uses, concerns: :pageable do
    resources :network_interfaces, concerns: :pageable
  end
  
  ##############################################################################
  # :network_interfaces
  resources :network_interfaces, concerns: :pageable

  ##############################################################################
  # :consoles
  resources :consoles, concerns: :pageable
  
  resources :onemdl_settings, :only => [:index, :edit]
  
  match '/onemdl_settings',      to: 'onemdl_settings#index',    via: 'get'
  match '/onemdl_settings/edit', to: 'onemdl_settings#edit',     via: 'get'
end

app/controllers/network_uses_controller.rb
# OneMDL is a ruby on rails based application designed to collate information
# about IT assets. It is designed to be most useful to System Administrators
# and Service Desk personal.
# 
# Copyright (C) 2013-2015 David Marsh
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

class NetworkUsesController < ApplicationController
  respond_to :html, :xml, :json
  helper_method :sort_column, :sort_direction
  
  def index
    @network_uses = NetworkUse.order(sort_column + " " + sort_direction).page(params[:page])
    respond_with(@network_uses)
  end
  
  def show
    @network_use = NetworkUse.friendly.find(params[:id])
    respond_with(@network_use)
  end
  
  def new
    @network_use = NetworkUse.new
    respond_with(@network_use)
  end
  
  def create
    @network_use = NetworkUse.new(network_use_params)
    
    if @network_use.save
      # write a create message to the activity log
      @network_use.create_activity :create, owner: current_user
      flash[:info] = "Successfully created network use '" + @network_use.name + "'"
    else
      flash[:error] = "Could not create network use '" + @network_use.name + "'"
    end
    
    respond_with(@network_use)
  end
  
  def edit
    @network_use = NetworkUse.friendly.find(params[:id])
    respond_with(@network_use)
  end
  
  def update
    @network_use = NetworkUse.friendly.find(params[:id])
    
    if @network_use.update_attributes(network_use_params)
      # write an update message to the activity log
      @network_use.create_activity :update, owner: current_user
      flash[:info] = "Successfully updated network use '" + @network_use.name + "'"
    else
      flash[:error] = "Could not update network use '" + @network_use.name + "'"
    end
    
    respond_with(@network_use)
  end
  
  def destroy
    @network_use = NetworkUse.friendly.find(params[:id])
    
    # write an update message to the activity log, it fails with a "cannot call create unless the parent is saved" inside the if statement, so I've put it here. It works out anyway, as we can show both successes and failures
    @network_use.create_activity :destroy, owner: current_user
    if @network_use.destroy
      flash[:info] = "Successfully deleted network use '" + @network_use.name + "'"
    else
      flash[:error] = "Could not delete network use '" + @network_use.name + "'"
    end
    
    respond_with(@network_use)
  end
  
  private
  
  # for sorting columns
  def sort_column
    NetworkUse.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end
  
  # for allowing editing on fields
  def network_use_params
    params.require(:network_use).permit!
  end
end

app/views/network_uses/_form.html.haml
= simple_form_for @network_use do |f|
  = f.error_notification
  
  = f.input :name
  = f.input       :description,     hint: "#{t('hint_description')} network use"
  
  = f.error :base
  = f.button :submit, :class => 'btn btn-primary'
  .btn-group.task_controller
    %a{:class => 'btn btn-danger dropdown-toggle', 'data-toggle' => 'dropdown', :href => '#'}
      #{t('delete')}.humanize
      %span{:class => 'caret'}
    %ul.dropdown-menu
      %li= link_to "Delete '#{f.object.name}'?", @network_use, data: { confirm: 'Are you sure?' }, :method => :delete
  or
  = link_to "#{t('cancel')}".humanize, :back

app/views/network_uses/_head.html.haml
- content_for(:title, t('network_use').pluralize.humanize)

- content_for(:index_tab, network_uses_path)
- content_for(:new_tab, new_network_use_path)

= render 'layouts/heading'
= render 'layouts/tabs'

app/views/network_uses/edit.html.haml
- content_for(:show_button_path, network_use_path(@network_use))

= render 'head'

= render 'form'

app/views/network_uses/index.html.haml
/ NetworkUse

=render 'head'

- if @network_uses.empty?
  %p= empty_msg('network_use', '')
- else
  %table.table.table-hover.table-condensed
    %tbody
      %thead
        %th
          = sortable "slug"
          %span{:class => 'caret'}
        %th
          = sortable "name"
          %span{:class => 'caret'}
        %th= sortable "description"
        %th= link_to t('network_interface').pluralize.humanize, network_interfaces_path
      - @network_uses.each do |r|
        %tr
          %td= link_to r.slug, r
          %td= link_to r.name, r
          %td= r.description
          %td= link_to r.network_interfaces.count, network_use_network_interfaces_path(r.slug)

  = paginate @network_uses

app/views/network_uses/show.html.haml
/ NetworkUse
- content_for(:edit_button_path, edit_network_use_path)

= render 'head'

= show_for @network_use do |f|
  .well
    %b= f.attribute :name
    = simple_format f.attribute :description
  .well
    = f.association :network_interfaces do
      %ul
        - @network_use.network_interfaces.each do |network_interfaces|
          %li= link_to network_interfaces.name + " (" + network_interfaces.ipaddress + " on " + @system.name + ")", network_interfaces_path(network_interfaces.id)
    - if @network_use.network_interfaces.empty?
      %p= empty_msg('network_interface', 'network_use')
  .well.muted
    = f.attribute :created_at, :format => :iso8601
    = f.attribute :updated_at, :format => :iso8601